layerOne = []
layerTwo = []
layerThree = []
layerFour = []
layerFive = []
layerSix = []
layerSeven = []
layerEight = []
layerNine = []
layerTen = []

allLayers = [layerOne, layerTwo, layerThree, layerFour, layerFive, layerSix, layerSeven, layerEight, layerNine, layerTen]
allLayerNames = ["layerOne", "layerTwo", "layerThree", "layerFour", "layerFive", "layerSix", "layerSeven", "layerEight", "layerNine", "layerTen"]
